# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 881cfaef359ebfde84945add475fdb996dfa0145566cec992fd8bd47dc0e7a0ca73cef279af8d06345847f08fc0ec6d7cb72259db6d59bd4542a504adada096a

test:
  secret_key_base: dab81754d232c07271ddced149d9fa7d0d9664de2062c7e298ca7b096f9e9d1ce2eb7671f496e0b11ed65214d6b908943573c694652f97d95793258ec6d2cfd8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 1fd3bfa7d7ca1903064c3541d803cb059e2a2597aab5df0fcef2b8543bc2950da4f208ae21d6ba697caed448bb206a880b64ff10d6e8ea24230ed7cb5153ef08
