\connect immobile
\encoding UTF8


-- CREATE OR REPLACE FUNCTION staging.merge_messages()
--   RETURNS void AS
-- $BODY$
-- DECLARE
--     r RECORD;
-- BEGIN
--     FOR r IN SELECT
--       identifier,
--       name, 
--       unit,
--       category, 
--       value_type, 
--       format_string, 
--       is_calculated, 
--       aggregation_func,
--       cal_message_id1, 
--       cal_message_id2, 
--       cal_operator, 
--       default_value, 
--       module 
--     FROM staging.messages
--     LOOP
--         UPDATE settings.messages SET
--           name = r.name, 
--           unit = r.unit,
--           category = r.category,
--           value_type = r.value_type,
--           format_string = r.format_string,
--           is_calculated = r.is_calculated,
--           aggregation_func = r.aggregation_func,
--           cal_message_id1 = r.cal_message_id1,
--           cal_message_id2 = r.cal_message_id2,
--           cal_operator = r.cal_operator,
--           default_value = r.default_value,
--           module = r.module
--         WHERE identifier = r.identifier;
--         IF NOT FOUND THEN
--         INSERT INTO settings.messages (
--           identifier,
--           name, 
--           unit,
--           category, 
--           value_type, 
--           format_string, 
--           is_calculated, 
--           aggregation_func,
--           cal_message_id1, 
--           cal_message_id2, 
--           cal_operator, 
--           default_value,
--           module
--         )
--         VALUES (
--           r.identifier,
--           r.name, 
--           r.unit,
--           r.category, 
--           r.value_type, 
--           r.format_string, 
--           r.is_calculated, 
--           r.aggregation_func,
--           r.cal_message_id1, 
--           r.cal_message_id2, 
--           r.cal_operator, 
--           r.default_value,
--           r.module
--         );
--         END IF;
--     END LOOP;
-- END;
-- $BODY$
--   LANGUAGE plpgsql VOLATILE
--   COST 100;
-- ALTER FUNCTION staging.merge_messages()
--   OWNER TO postgres;
  

